//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace X1UserSynchroService.UserSynchroWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserSynchroWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UserSynchroWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserFingerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserFingerInfoByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserGroup2UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserGroup2UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserGroup2UserGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserGroup2UserGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserLoginExOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserLoginExListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserLoginExOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserSynchroWebService() {
            this.Url = global::X1UserSynchroService.Properties.Settings.Default.X1UserSynchroService_UserSynchroWebService_UserSynchroWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        public event DeleteUserByIDCompletedEventHandler DeleteUserByIDCompleted;
        
        /// <remarks/>
        public event UpdateUserFingerInfoCompletedEventHandler UpdateUserFingerInfoCompleted;
        
        /// <remarks/>
        public event DeleteUserFingerInfoByIDCompletedEventHandler DeleteUserFingerInfoByIDCompleted;
        
        /// <remarks/>
        public event UpdateUserGroupsCompletedEventHandler UpdateUserGroupsCompleted;
        
        /// <remarks/>
        public event DeleteUserGroupCompletedEventHandler DeleteUserGroupCompleted;
        
        /// <remarks/>
        public event UpdateUserGroup2UserCompletedEventHandler UpdateUserGroup2UserCompleted;
        
        /// <remarks/>
        public event DeleteUserGroup2UserCompletedEventHandler DeleteUserGroup2UserCompleted;
        
        /// <remarks/>
        public event UpdateUserGroup2UserGroupCompletedEventHandler UpdateUserGroup2UserGroupCompleted;
        
        /// <remarks/>
        public event DeleteUserGroup2UserGroupCompletedEventHandler DeleteUserGroup2UserGroupCompleted;
        
        /// <remarks/>
        public event UpdateUserLoginCompletedEventHandler UpdateUserLoginCompleted;
        
        /// <remarks/>
        public event DeleteUserLoginCompletedEventHandler DeleteUserLoginCompleted;
        
        /// <remarks/>
        public event UpdateUserLoginExCompletedEventHandler UpdateUserLoginExCompleted;
        
        /// <remarks/>
        public event UpdateUserLoginExListCompletedEventHandler UpdateUserLoginExListCompleted;
        
        /// <remarks/>
        public event DeleteUserLoginExCompletedEventHandler DeleteUserLoginExCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUser(User ur) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserAsync(User ur) {
            this.UpdateUserAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(User ur, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        ur}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserByID(string userID) {
            object[] results = this.Invoke("DeleteUserByID", new object[] {
                        userID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserByIDAsync(string userID) {
            this.DeleteUserByIDAsync(userID, null);
        }
        
        /// <remarks/>
        public void DeleteUserByIDAsync(string userID, object userState) {
            if ((this.DeleteUserByIDOperationCompleted == null)) {
                this.DeleteUserByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserByIDOperationCompleted);
            }
            this.InvokeAsync("DeleteUserByID", new object[] {
                        userID}, this.DeleteUserByIDOperationCompleted, userState);
        }
        
        private void OnDeleteUserByIDOperationCompleted(object arg) {
            if ((this.DeleteUserByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserByIDCompleted(this, new DeleteUserByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserFingerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserFingerInfo(UserFingerInfo ur) {
            object[] results = this.Invoke("UpdateUserFingerInfo", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserFingerInfoAsync(UserFingerInfo ur) {
            this.UpdateUserFingerInfoAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserFingerInfoAsync(UserFingerInfo ur, object userState) {
            if ((this.UpdateUserFingerInfoOperationCompleted == null)) {
                this.UpdateUserFingerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserFingerInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateUserFingerInfo", new object[] {
                        ur}, this.UpdateUserFingerInfoOperationCompleted, userState);
        }
        
        private void OnUpdateUserFingerInfoOperationCompleted(object arg) {
            if ((this.UpdateUserFingerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserFingerInfoCompleted(this, new UpdateUserFingerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserFingerInfoByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserFingerInfoByID(string userID) {
            object[] results = this.Invoke("DeleteUserFingerInfoByID", new object[] {
                        userID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserFingerInfoByIDAsync(string userID) {
            this.DeleteUserFingerInfoByIDAsync(userID, null);
        }
        
        /// <remarks/>
        public void DeleteUserFingerInfoByIDAsync(string userID, object userState) {
            if ((this.DeleteUserFingerInfoByIDOperationCompleted == null)) {
                this.DeleteUserFingerInfoByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserFingerInfoByIDOperationCompleted);
            }
            this.InvokeAsync("DeleteUserFingerInfoByID", new object[] {
                        userID}, this.DeleteUserFingerInfoByIDOperationCompleted, userState);
        }
        
        private void OnDeleteUserFingerInfoByIDOperationCompleted(object arg) {
            if ((this.DeleteUserFingerInfoByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserFingerInfoByIDCompleted(this, new DeleteUserFingerInfoByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserGroups", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserGroups(UserGroup ur) {
            object[] results = this.Invoke("UpdateUserGroups", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserGroupsAsync(UserGroup ur) {
            this.UpdateUserGroupsAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserGroupsAsync(UserGroup ur, object userState) {
            if ((this.UpdateUserGroupsOperationCompleted == null)) {
                this.UpdateUserGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserGroupsOperationCompleted);
            }
            this.InvokeAsync("UpdateUserGroups", new object[] {
                        ur}, this.UpdateUserGroupsOperationCompleted, userState);
        }
        
        private void OnUpdateUserGroupsOperationCompleted(object arg) {
            if ((this.UpdateUserGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserGroupsCompleted(this, new UpdateUserGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserGroup(string userGroupID) {
            object[] results = this.Invoke("DeleteUserGroup", new object[] {
                        userGroupID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserGroupAsync(string userGroupID) {
            this.DeleteUserGroupAsync(userGroupID, null);
        }
        
        /// <remarks/>
        public void DeleteUserGroupAsync(string userGroupID, object userState) {
            if ((this.DeleteUserGroupOperationCompleted == null)) {
                this.DeleteUserGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserGroupOperationCompleted);
            }
            this.InvokeAsync("DeleteUserGroup", new object[] {
                        userGroupID}, this.DeleteUserGroupOperationCompleted, userState);
        }
        
        private void OnDeleteUserGroupOperationCompleted(object arg) {
            if ((this.DeleteUserGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserGroupCompleted(this, new DeleteUserGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserGroup2User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserGroup2User(UserGroup2User ur) {
            object[] results = this.Invoke("UpdateUserGroup2User", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserGroup2UserAsync(UserGroup2User ur) {
            this.UpdateUserGroup2UserAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserGroup2UserAsync(UserGroup2User ur, object userState) {
            if ((this.UpdateUserGroup2UserOperationCompleted == null)) {
                this.UpdateUserGroup2UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserGroup2UserOperationCompleted);
            }
            this.InvokeAsync("UpdateUserGroup2User", new object[] {
                        ur}, this.UpdateUserGroup2UserOperationCompleted, userState);
        }
        
        private void OnUpdateUserGroup2UserOperationCompleted(object arg) {
            if ((this.UpdateUserGroup2UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserGroup2UserCompleted(this, new UpdateUserGroup2UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserGroup2User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserGroup2User(string userGroup2UserID) {
            object[] results = this.Invoke("DeleteUserGroup2User", new object[] {
                        userGroup2UserID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserGroup2UserAsync(string userGroup2UserID) {
            this.DeleteUserGroup2UserAsync(userGroup2UserID, null);
        }
        
        /// <remarks/>
        public void DeleteUserGroup2UserAsync(string userGroup2UserID, object userState) {
            if ((this.DeleteUserGroup2UserOperationCompleted == null)) {
                this.DeleteUserGroup2UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserGroup2UserOperationCompleted);
            }
            this.InvokeAsync("DeleteUserGroup2User", new object[] {
                        userGroup2UserID}, this.DeleteUserGroup2UserOperationCompleted, userState);
        }
        
        private void OnDeleteUserGroup2UserOperationCompleted(object arg) {
            if ((this.DeleteUserGroup2UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserGroup2UserCompleted(this, new DeleteUserGroup2UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserGroup2UserGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserGroup2UserGroup(UserGroup2UserGroup ur) {
            object[] results = this.Invoke("UpdateUserGroup2UserGroup", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserGroup2UserGroupAsync(UserGroup2UserGroup ur) {
            this.UpdateUserGroup2UserGroupAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserGroup2UserGroupAsync(UserGroup2UserGroup ur, object userState) {
            if ((this.UpdateUserGroup2UserGroupOperationCompleted == null)) {
                this.UpdateUserGroup2UserGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserGroup2UserGroupOperationCompleted);
            }
            this.InvokeAsync("UpdateUserGroup2UserGroup", new object[] {
                        ur}, this.UpdateUserGroup2UserGroupOperationCompleted, userState);
        }
        
        private void OnUpdateUserGroup2UserGroupOperationCompleted(object arg) {
            if ((this.UpdateUserGroup2UserGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserGroup2UserGroupCompleted(this, new UpdateUserGroup2UserGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserGroup2UserGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserGroup2UserGroup(string UserGroup2UserGroupID) {
            object[] results = this.Invoke("DeleteUserGroup2UserGroup", new object[] {
                        UserGroup2UserGroupID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserGroup2UserGroupAsync(string UserGroup2UserGroupID) {
            this.DeleteUserGroup2UserGroupAsync(UserGroup2UserGroupID, null);
        }
        
        /// <remarks/>
        public void DeleteUserGroup2UserGroupAsync(string UserGroup2UserGroupID, object userState) {
            if ((this.DeleteUserGroup2UserGroupOperationCompleted == null)) {
                this.DeleteUserGroup2UserGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserGroup2UserGroupOperationCompleted);
            }
            this.InvokeAsync("DeleteUserGroup2UserGroup", new object[] {
                        UserGroup2UserGroupID}, this.DeleteUserGroup2UserGroupOperationCompleted, userState);
        }
        
        private void OnDeleteUserGroup2UserGroupOperationCompleted(object arg) {
            if ((this.DeleteUserGroup2UserGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserGroup2UserGroupCompleted(this, new DeleteUserGroup2UserGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserLogin(UserLogin ur) {
            object[] results = this.Invoke("UpdateUserLogin", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserLoginAsync(UserLogin ur) {
            this.UpdateUserLoginAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserLoginAsync(UserLogin ur, object userState) {
            if ((this.UpdateUserLoginOperationCompleted == null)) {
                this.UpdateUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserLoginOperationCompleted);
            }
            this.InvokeAsync("UpdateUserLogin", new object[] {
                        ur}, this.UpdateUserLoginOperationCompleted, userState);
        }
        
        private void OnUpdateUserLoginOperationCompleted(object arg) {
            if ((this.UpdateUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserLoginCompleted(this, new UpdateUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserLogin(string userID) {
            object[] results = this.Invoke("DeleteUserLogin", new object[] {
                        userID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserLoginAsync(string userID) {
            this.DeleteUserLoginAsync(userID, null);
        }
        
        /// <remarks/>
        public void DeleteUserLoginAsync(string userID, object userState) {
            if ((this.DeleteUserLoginOperationCompleted == null)) {
                this.DeleteUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserLoginOperationCompleted);
            }
            this.InvokeAsync("DeleteUserLogin", new object[] {
                        userID}, this.DeleteUserLoginOperationCompleted, userState);
        }
        
        private void OnDeleteUserLoginOperationCompleted(object arg) {
            if ((this.DeleteUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserLoginCompleted(this, new DeleteUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserLoginEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserLoginEx(UserLoginEx ur) {
            object[] results = this.Invoke("UpdateUserLoginEx", new object[] {
                        ur});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserLoginExAsync(UserLoginEx ur) {
            this.UpdateUserLoginExAsync(ur, null);
        }
        
        /// <remarks/>
        public void UpdateUserLoginExAsync(UserLoginEx ur, object userState) {
            if ((this.UpdateUserLoginExOperationCompleted == null)) {
                this.UpdateUserLoginExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserLoginExOperationCompleted);
            }
            this.InvokeAsync("UpdateUserLoginEx", new object[] {
                        ur}, this.UpdateUserLoginExOperationCompleted, userState);
        }
        
        private void OnUpdateUserLoginExOperationCompleted(object arg) {
            if ((this.UpdateUserLoginExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserLoginExCompleted(this, new UpdateUserLoginExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserLoginExList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateUserLoginExList(UserLoginEx[] pUserLoginExList) {
            object[] results = this.Invoke("UpdateUserLoginExList", new object[] {
                        pUserLoginExList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserLoginExListAsync(UserLoginEx[] pUserLoginExList) {
            this.UpdateUserLoginExListAsync(pUserLoginExList, null);
        }
        
        /// <remarks/>
        public void UpdateUserLoginExListAsync(UserLoginEx[] pUserLoginExList, object userState) {
            if ((this.UpdateUserLoginExListOperationCompleted == null)) {
                this.UpdateUserLoginExListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserLoginExListOperationCompleted);
            }
            this.InvokeAsync("UpdateUserLoginExList", new object[] {
                        pUserLoginExList}, this.UpdateUserLoginExListOperationCompleted, userState);
        }
        
        private void OnUpdateUserLoginExListOperationCompleted(object arg) {
            if ((this.UpdateUserLoginExListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserLoginExListCompleted(this, new UpdateUserLoginExListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserLoginEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteUserLoginEx(string userLoginName) {
            object[] results = this.Invoke("DeleteUserLoginEx", new object[] {
                        userLoginName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserLoginExAsync(string userLoginName) {
            this.DeleteUserLoginExAsync(userLoginName, null);
        }
        
        /// <remarks/>
        public void DeleteUserLoginExAsync(string userLoginName, object userState) {
            if ((this.DeleteUserLoginExOperationCompleted == null)) {
                this.DeleteUserLoginExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserLoginExOperationCompleted);
            }
            this.InvokeAsync("DeleteUserLoginEx", new object[] {
                        userLoginName}, this.DeleteUserLoginExOperationCompleted, userState);
        }
        
        private void OnDeleteUserLoginExOperationCompleted(object arg) {
            if ((this.DeleteUserLoginExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserLoginExCompleted(this, new DeleteUserLoginExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string codeField;
        
        private bool genderField;
        
        private string loginNameField;
        
        private string passwordField;
        
        private string tag1Field;
        
        private string tag2Field;
        
        private string tag3Field;
        
        private string certificateField;
        
        private bool forceCardField;
        
        private System.Nullable<int> jobStatusField;
        
        private string iCNumber1Field;
        
        private string iCNumber2Field;
        
        private string iCNumber3Field;
        
        private string jobNumberField;
        
        private string iDNumberField;
        
        private string fingerprintField;
        
        private string email1Field;
        
        private string email2Field;
        
        private string telephone1Field;
        
        private string telephone2Field;
        
        private string companyAddrField;
        
        private string homeAddrField;
        
        private System.Nullable<System.DateTime> lastLoginDateTimeField;
        
        private string createUserNameField;
        
        private System.Guid createUserIDField;
        
        private System.Nullable<System.DateTime> createDateTimeField;
        
        private string modifyUserNameField;
        
        private System.Guid modifyUserIDField;
        
        private System.Nullable<System.DateTime> modifyDateTimeField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public bool Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Tag1 {
            get {
                return this.tag1Field;
            }
            set {
                this.tag1Field = value;
            }
        }
        
        /// <remarks/>
        public string Tag2 {
            get {
                return this.tag2Field;
            }
            set {
                this.tag2Field = value;
            }
        }
        
        /// <remarks/>
        public string Tag3 {
            get {
                return this.tag3Field;
            }
            set {
                this.tag3Field = value;
            }
        }
        
        /// <remarks/>
        public string Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        public bool ForceCard {
            get {
                return this.forceCardField;
            }
            set {
                this.forceCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> JobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ICNumber1 {
            get {
                return this.iCNumber1Field;
            }
            set {
                this.iCNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string ICNumber2 {
            get {
                return this.iCNumber2Field;
            }
            set {
                this.iCNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string ICNumber3 {
            get {
                return this.iCNumber3Field;
            }
            set {
                this.iCNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string JobNumber {
            get {
                return this.jobNumberField;
            }
            set {
                this.jobNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Fingerprint {
            get {
                return this.fingerprintField;
            }
            set {
                this.fingerprintField = value;
            }
        }
        
        /// <remarks/>
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
            }
        }
        
        /// <remarks/>
        public string Email2 {
            get {
                return this.email2Field;
            }
            set {
                this.email2Field = value;
            }
        }
        
        /// <remarks/>
        public string Telephone1 {
            get {
                return this.telephone1Field;
            }
            set {
                this.telephone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Telephone2 {
            get {
                return this.telephone2Field;
            }
            set {
                this.telephone2Field = value;
            }
        }
        
        /// <remarks/>
        public string CompanyAddr {
            get {
                return this.companyAddrField;
            }
            set {
                this.companyAddrField = value;
            }
        }
        
        /// <remarks/>
        public string HomeAddr {
            get {
                return this.homeAddrField;
            }
            set {
                this.homeAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLoginDateTime {
            get {
                return this.lastLoginDateTimeField;
            }
            set {
                this.lastLoginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifyUserName {
            get {
                return this.modifyUserNameField;
            }
            set {
                this.modifyUserNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ModifyUserID {
            get {
                return this.modifyUserIDField;
            }
            set {
                this.modifyUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifyDateTime {
            get {
                return this.modifyDateTimeField;
            }
            set {
                this.modifyDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLoginEx {
        
        private string userLoginNameField;
        
        private string userLoginEx1Field;
        
        private string userLoginEx2Field;
        
        private string userLoginEx3Field;
        
        private string userLoginEx4Field;
        
        private string userLoginEx5Field;
        
        /// <remarks/>
        public string UserLoginName {
            get {
                return this.userLoginNameField;
            }
            set {
                this.userLoginNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserLoginEx1 {
            get {
                return this.userLoginEx1Field;
            }
            set {
                this.userLoginEx1Field = value;
            }
        }
        
        /// <remarks/>
        public string UserLoginEx2 {
            get {
                return this.userLoginEx2Field;
            }
            set {
                this.userLoginEx2Field = value;
            }
        }
        
        /// <remarks/>
        public string UserLoginEx3 {
            get {
                return this.userLoginEx3Field;
            }
            set {
                this.userLoginEx3Field = value;
            }
        }
        
        /// <remarks/>
        public string UserLoginEx4 {
            get {
                return this.userLoginEx4Field;
            }
            set {
                this.userLoginEx4Field = value;
            }
        }
        
        /// <remarks/>
        public string UserLoginEx5 {
            get {
                return this.userLoginEx5Field;
            }
            set {
                this.userLoginEx5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLogin {
        
        private System.Guid userIDField;
        
        private System.DateTime loginTimeField;
        
        private string computerNameField;
        
        private string iPAddressField;
        
        /// <remarks/>
        public System.Guid UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LoginTime {
            get {
                return this.loginTimeField;
            }
            set {
                this.loginTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ComputerName {
            get {
                return this.computerNameField;
            }
            set {
                this.computerNameField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserGroup2UserGroup {
        
        private System.Guid idField;
        
        private System.Guid superiorIDField;
        
        private System.Guid lowerIDField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SuperiorID {
            get {
                return this.superiorIDField;
            }
            set {
                this.superiorIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid LowerID {
            get {
                return this.lowerIDField;
            }
            set {
                this.lowerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserGroup2User {
        
        private System.Guid idField;
        
        private System.Guid userGroupIDField;
        
        private System.Guid userIDField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserGroupID {
            get {
                return this.userGroupIDField;
            }
            set {
                this.userGroupIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserGroup {
        
        private System.Guid idField;
        
        private System.Guid systemIDField;
        
        private string nameField;
        
        private string descriptionField;
        
        private System.Nullable<int> categoryField;
        
        private string categoryNameField;
        
        private System.Nullable<int> sysRelNumberField;
        
        private string createUserNameField;
        
        private System.Guid createUserIDField;
        
        private System.Nullable<System.DateTime> createDateTimeField;
        
        private string modifyUserNameField;
        
        private System.Guid modifyUserIDField;
        
        private System.Nullable<System.DateTime> modifyDateTimeField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SysRelNumber {
            get {
                return this.sysRelNumberField;
            }
            set {
                this.sysRelNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ModifyUserName {
            get {
                return this.modifyUserNameField;
            }
            set {
                this.modifyUserNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ModifyUserID {
            get {
                return this.modifyUserIDField;
            }
            set {
                this.modifyUserIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifyDateTime {
            get {
                return this.modifyDateTimeField;
            }
            set {
                this.modifyDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserFingerInfo {
        
        private System.Guid userIDField;
        
        private string fingerInfoStr1Field;
        
        private string fingerInfoStr2Field;
        
        private string fingerInfoStr3Field;
        
        /// <remarks/>
        public System.Guid UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string FingerInfoStr1 {
            get {
                return this.fingerInfoStr1Field;
            }
            set {
                this.fingerInfoStr1Field = value;
            }
        }
        
        /// <remarks/>
        public string FingerInfoStr2 {
            get {
                return this.fingerInfoStr2Field;
            }
            set {
                this.fingerInfoStr2Field = value;
            }
        }
        
        /// <remarks/>
        public string FingerInfoStr3 {
            get {
                return this.fingerInfoStr3Field;
            }
            set {
                this.fingerInfoStr3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserByIDCompletedEventHandler(object sender, DeleteUserByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserFingerInfoCompletedEventHandler(object sender, UpdateUserFingerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserFingerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserFingerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserFingerInfoByIDCompletedEventHandler(object sender, DeleteUserFingerInfoByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserFingerInfoByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserFingerInfoByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserGroupsCompletedEventHandler(object sender, UpdateUserGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserGroupCompletedEventHandler(object sender, DeleteUserGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserGroup2UserCompletedEventHandler(object sender, UpdateUserGroup2UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserGroup2UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserGroup2UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserGroup2UserCompletedEventHandler(object sender, DeleteUserGroup2UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserGroup2UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserGroup2UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserGroup2UserGroupCompletedEventHandler(object sender, UpdateUserGroup2UserGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserGroup2UserGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserGroup2UserGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserGroup2UserGroupCompletedEventHandler(object sender, DeleteUserGroup2UserGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserGroup2UserGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserGroup2UserGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserLoginCompletedEventHandler(object sender, UpdateUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserLoginCompletedEventHandler(object sender, DeleteUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserLoginExCompletedEventHandler(object sender, UpdateUserLoginExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserLoginExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserLoginExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserLoginExListCompletedEventHandler(object sender, UpdateUserLoginExListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserLoginExListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserLoginExListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteUserLoginExCompletedEventHandler(object sender, DeleteUserLoginExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserLoginExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserLoginExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591